application: saludable-foods-sas
version: 20160901
runtime: python27
api_version: 1
threadsafe: true

handlers:
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  
- url: /static
  static_dir: static
  application_readable: true
  
- url: /.*
  script: main.application
  #script: update_schema_handler.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
  
builtins:
- remote_api: on
- deferred: on