application: saludable-foods-sas
version: 20170314
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- mail

handlers:

- url: /facturasVencidas
  script: cron_handler.app
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  
- url: /static
  static_dir: static
  application_readable: true
  
- url: /_ah/mail/.+
  script: handle_incoming_email.app
  login: admin
 #saldo@saludable-foods-sas.appspotmail.com

- url: /update_schema
  script: update_schema_handler.app


- url: /.*
  script: main.application
  #script: update_schema_handler.app
  

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
  
builtins:
- remote_api: on
- deferred: on