import webapp2
from views.views import *

application = webapp2.WSGIApplication([
    ('/test', Test),
    ('/login',LogIn),
    ('/logout',LogOut),
    ('/home', Home),
    ('/addEntity',AddEntity),
    ('/saveEntity', SaveEntity),
    ('/showEntities',ShowEntities),
    ('/entityData', EntityData),
    ('/deleteEntity', DeleteEntity),
    ('/crearEgreso', CrearEgreso),
    ('/crearFactura', CrearFactura),
    ('/getPrice', GetPrice),
    ('/guardarFactura', GuardarFactura),
    ('/guardarEgreso', GuardarEgreso),
    ('/exportScript', ExportScript),
    ('/importScript', ImportScript),
    ('/mostrarFactura', MostrarFactura),
    ('/getVentas', GetVentas),
    ('/getProducto', GetProducto),
    ('/getPorcion', GetPorcion),
    ('/getClientes', GetClientes),
    ('/getEmpleados', GetEmpleados),
    ('/setNumero', SetNumber),
    ('/importCSV', ImportCSV),
    ('/importFacturas',ImportFacturas),
    ('/anularFactura', AnularFactura),
    ('/pivot',Pivot),
    ('/tablaDinamica',TablaDinamica),
    ('/getProductSales',GetProductSales),
    ('/getWidget',GetWidget),
    ('/getBienesoServicios',GetBienesoServicios),
    ('/getProveedores',GetProveedores),
    ('/addBienoservicio',Addbienoservicio)
], debug=True)